name: tc
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - ca-certificates=2022.9.24=ha878542_0
  - ld_impl_linux-64=2.39=hc81fddc_0
  - libffi=3.3=h58526e2_2
  - libgcc-ng=12.2.0=h65d4601_19
  - libgomp=12.2.0=h65d4601_19
  - libsqlite=3.40.0=h753d276_0
  - libstdcxx-ng=12.2.0=h46fd767_19
  - libzlib=1.2.13=h166bdaf_4
  - ncurses=6.3=h27087fc_1
  - openssl=1.1.1s=h166bdaf_0
  - pip=22.3.1=pyhd8ed1ab_0
  - python=3.9.6=h49503c6_1_cpython
  - readline=8.1.2=h0f457ee_0
  - sqlite=3.40.0=h4ff8645_0
  - tk=8.6.12=h27826a3_0
  - wheel=0.38.4=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - zlib=1.2.13=h166bdaf_4
  - pip:
      - accelerate==1.10.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.1
      - aiosignal==1.4.0
      - appdirs==1.4.4
      - asttokens==3.0.0
      - async-timeout==5.0.1
      - attrs==25.4.0
      - backcall==0.2.0
      - beartype==0.14.1
      - better-abc==0.0.3
      - certifi==2025.10.5
      - charset-normalizer==3.4.4
      - click==8.1.8
      - contourpy==1.3.0
      - cycler==0.12.1
      - datasets==2.12.0
      - decorator==5.2.1
      - dill==0.3.6
      - docker-pycreds==0.4.0
      - einops==0.7.0
      - exceptiongroup==1.3.0
      - executing==2.2.1
      - fancy-einsum==0.0.3
      - filelock==3.19.1
      - fonttools==4.60.1
      - frozenlist==1.8.0
      - fsspec==2025.9.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - hf-xet==1.1.10
      - huggingface-hub==0.36.0
      - idna==3.11
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - iniconfig==2.1.0
      - ipython==8.12.3
      - jaxtyping==0.2.36
      - jedi==0.19.2
      - jinja2==3.1.6
      - kiwisolver==1.4.7
      - markdown-it-py==3.0.0
      - markupsafe==3.0.3
      - matplotlib==3.7.1
      - matplotlib-inline==0.2.1
      - mdurl==0.1.2
      - mpmath==1.3.0
      - multidict==6.7.0
      - multiprocess==0.70.14
      - networkx==3.2.1
      - numpy==1.26.0
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - packaging==25.0
      - pandas==2.0.0
      - parso==0.8.5
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==11.3.0
      - plotly==5.18.0
      - pluggy==1.6.0
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - protobuf==4.25.8
      - psutil==7.1.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==15.0.2
      - pygments==2.19.2
      - pyparsing==3.2.5
      - pytest==8.4.2
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - regex==2025.10.23
      - requests==2.32.5
      - responses==0.18.0
      - rich==14.2.0
      - safetensors==0.6.2
      - sentencepiece==0.1.96
      - sentry-sdk==2.42.1
      - setproctitle==1.3.7
      - setuptools==67.7.2
      - six==1.17.0
      - smmap==5.0.2
      - stack-data==0.6.3
      - sympy==1.13.1
      - tenacity==9.1.2
      - tokenizers==0.22.1
      - tomli==2.3.0
      - torch==2.6.0
      - tqdm==4.65.0
      - traitlets==5.14.3
      - transformer-lens==2.16.1
      - transformers==4.57.1
      - transformers-stream-generator==0.0.5
      - triton==3.2.0
      - typeguard==4.4.4
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - urllib3==2.5.0
      - wandb==0.16.0
      - wcwidth==0.2.14
      - xxhash==3.6.0
      - yarl==1.22.0
      - zipp==3.23.0
prefix: /wuzhou/pentafleet/liangzihao/.conda/envs/tc
